version: "3.9"




services:

  backend:
    container_name: backend5
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

#     depends_on:
#       - db

#   db:
#     image: postgres
# #     ports:
# #       - "5432:5432"
# #     volumes:
# #       - postgres_data:/var/lib/postgresql/data
# #     environment:
# #       - POSTGRES_PASSWORD=Mohamad01
# #       - POSTGRES_USER=postgres
# #       - POSTGRES_DB=todo_cbv_db


  

  

# # volumes:
# #   postgres_data: